ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        shutdownGracePeriod = 2000
        shutdownUrl = "/shutdown"
    }
    application {
        modules = [ com.adnanfoisal.infinitydesign.backend.BackendApplicationKt.module ]
    }
}
